#!/bin/zsh

unsetopt PROMPT_SP

export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"

export MANPAGER="nvim +Man\!"

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

export DOT_SAGE="${XDG_CONFIG_HOME:-$HOME/.config}"/sage

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export GDBHISTFILE="${XDG_DATA_HOME:-$HOME/.config}"/gdb/history

export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSCHARSET=utf-8
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"

# For fixing the scaling of some java programs
export _JAVA_AWT_WM_NONREPARENTING=1
